project:
  type: default
  output-dir: output

# Demo project configuration for AI presentation
title-block-banner: false
toc: true
toc-depth: 2
number-sections: true
highlight-style: github

format:
  pdf:
    documentclass: article
    papersize: a4
    margin-left: 1in
    margin-right: 1in
    margin-top: 1.25in
    margin-bottom: 1.25in
    fontsize: 11pt
    linestretch: 1.15
    fig-cap-location: bottom
    tbl-cap-location: top
    pdf-engine: xelatex
    keep-tex: false
    # Professional typography
    mainfont: "Times New Roman"
    sansfont: "Helvetica Neue" 
    monofont: "Menlo"
    # Professional colors
    linkcolor: blue
    urlcolor: blue
    citecolor: blue
    
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    code-fold: true
    code-tools: true
    self-contained: true

# Execution options
execute:
  echo: false
  warning: false
  message: false
  cache: false