project:
  type: default

format:
  beamer:
    theme: metropolis
    colortheme: default
    fonttheme: default
    aspectratio: 169
    section-titles: false
    slide-level: 2
    toc: false
    incremental: false
    keep-tex: true
    pdf-engine: xelatex