project:
  type: website

website:
  title: "The Asymmetric Bet: AI for Engineering and Enterprise"
  navbar:
    left:
      - href: index.qmd
        text: Presentation
      - about.qmd

format:
  revealjs:
    theme: [default, custom.scss]
    css: styles.css
    toc: true
    slide-number: true
    show-slide-number: all
    transition: slide
    background-transition: fade
    controls: true
    progress: true
    center: true
    touch: true
    keyboard: true
    overview: true
    help: true
    auto-animate: true
    fragments: true
    embed-resources: true



